### ISSUE TITLE
Pb fenêtre sélection référentiel

### ISSUE THREAD

**Issue by Jojooct10** [jerem1508/magical_ui#106]
![image](https://user-images.githubusercontent.com/34550712/34927709-8b6d8ba8-f9b8-11e7-9995-8448ac390b8b.png)

**Comment by Jojooct10** [comment]
et pb chargement référentiel à l'étape suivante
![image](https://user-images.githubusercontent.com/34550712/34927777-03b24022-f9b9-11e7-8e3a-14a333f17dae.png)

**Comment by Leobouloc** [comment]
Ok pour l'erreur php mais quel est le problème avec le chargement ?
