### ISSUE TITLE
Erreur php d'origine inconnue

### ISSUE THREAD

**Issue by Leobouloc** [jerem1508/magical_ui#108]
![image](https://user-images.githubusercontent.com/7846153/34941425-f0753218-f9f3-11e7-8701-9e215e8ec5eb.png)

**Comment by Leobouloc** [comment]
Autre erreur: impossible d'acceder au TDB:
![image](https://user-images.githubusercontent.com/7846153/34941459-1c490554-f9f4-11e7-9019-a57995a2395a.png)

**Comment by jerem1508** [comment]
non reproduit
