### ISSUE TITLE
Affichage de l'ancienne page de normalisation

### ISSUE THREAD

**Issue by toutestprismemeca** [jerem1508/magical_ui#193]
Quand on supprime un fichier et que l'on clique sur poursuivre le projet pour charger à nouveau un fichier, on tombe sur l'ancienne page de normalisation

![screenshot-machine_a_donnees](https://user-images.githubusercontent.com/36891819/36786704-a99cd81c-1c87-11e8-894b-d92d7183164c.png)

**Comment by Leobouloc** [comment]
même problème que: https://github.com/jerem1508/magical_ui/issues/160
