### ISSUE TITLE
[Labellistation] Enlever le taux de précision souhaité (pour l'instant)

### ISSUE THREAD

**Issue by Leobouloc** [jerem1508/magical_ui#209]

**Comment by jerem1508** [comment]
qu'est ce que tu appelles le taux de précision souhaité ?
seuil ?

**Comment by Leobouloc** [comment]
Le déroulant avec 100% 95% et "tout matcher" (ou quelque chose comme ça). Si tu fais déjà les appels API associés on peut le laisser mais s'il n'est lié à rien c'est mieux de l'enlever.

**Comment by Leobouloc** [comment]
Le déroulant avec 100% 95% et "tout matcher" (ou quelque chose comme ça).
Si tu fais déjà les appels API associés on peut le laisser mais s'il n'est
lié à rien c'est mieux de l'enlever.

**Comment by jerem1508** [comment]
ah ok, j'était sur la page de résultats
