### ISSUE TITLE
[Association de colonnes] "Association parfaite" Ne fait rien ?

### ISSUE THREAD

**Issue by Leobouloc** [jerem1508/magical_ui#219]

**Comment by jerem1508** [comment]
Elle passe "exact_only" à true.Tu le vois quand tu affiches le JSON.
L'API ne le reçoit pas ?

**Comment by Leobouloc** [comment]
Mhmm. Ok je vais investiguer.

**Comment by Leobouloc** [comment]
Le problème est dans l'API:
https://github.com/entrepreneur-interet-general/the-magical-csv-merge-machine/issues/98
