### ISSUE TITLE
es_fetch

### ISSUE THREAD

**Issue by jerem1508** [jerem1508/magical_ui#229]
J'ai l'impression que es_fetch sur _ID et DESC ne fonctionne pas correctement. Le résultat est identique a ASC

**Comment by Leobouloc** [comment]
effectivement, c'est le cas... Je vais regarder.

**Comment by Leobouloc** [comment]
https://github.com/entrepreneur-interet-general/the-magical-csv-merge-machine/commit/ff1d1f995fb945c935be5657f60b16a19a97547d
