### ISSUE TITLE
export des fichiers

### ISSUE THREAD

**Issue by yaca29** [jerem1508/magical_ui#86]
Ne faudrait-il pas baliser les champs avec des "", car on se retrouve avec des problèmes d'import dans le cas où l'on a des virgules dans le contenu d'un champ (puisque la virgule est considéré comme le séparateur)

c'est assez étonnant d'avoir dans la log l'ensemble du contenu du fichier exporté

**Comment by Leobouloc** [comment]
Le problème est il-encore d'actualité? Si oui, as-tu un fichier qui pose problème pour essayer?

**Comment by Leobouloc** [comment]
pas reproduit récemment
